### ISSUE TITLE
星星金字塔地獄

### ISSUE THREAD

**Issue by PsMonkey** [PsMonkey/trainAdam#1]
當使用者輸入一個數字 n，要印出對應的圖形。下列圖形是 `n = 5` 的狀況，你 **不用** 實作使用者輸入數字的功能，可以直接這樣做

```Java
int n = 5;

for (int i = 0; i < n; i++) {
    //blahblah
}
```

重點是「5」這個 magic number 除了在一開始宣告之外，後續程式碼不能出現。

--------

## part 1 ##

```
*
**
***
****
*****
```

## part 2 ##

```
*
**
***
****
*****
****
***
**
*
```

### part 2-1 ###
* 只能用兩個迴圈

## part 3 ##

```
    *
   ***
  *****
 *******
*********
```

## part 4 ##

```
*       *
**     **
***   ***
**** ****
*********
```

**Comment by q123600** [comment]
###Part 1###(怕自己搞錯就全附上了xD)
public class First {
	public static void main(String[] args) {
		
		for(int i = 0 ; i < 5 ; i += 1){
			for(int b = 0 ; b < 5 ; b += 1){
				if(i >= b){
					System.out.print("*");
				}
			}
		System.out.println();
		}
	}
}

**Comment by q123600** [comment]
public class First {
	public static void main(String[] args) {
		
		for(int i = 0 ; i < 9 ; i += 1){
			for(int b = 0 ; b < 5 ; b += 1){
				if(i <= 4 && i >= b){
					System.out.print("*");
				}
				else if(i > 4 && i + b <= 8){
					System.out.print("*");
				}
			}
		System.out.println();
		}
	}
}

**Comment by q123600** [comment]
that was ###Part 2###

**Comment by q123600** [comment]
###Part 3###
public class First {
	public static void main(String[] args) {
		
		for(int i = 0 ; i < 5 ; i += 1){
			for(int b = 0 ; b < 9 ; b += 1){
				if(b <= 4 && b + i >= 4){
					System.out.print("*");
				}
				else if(b > 4 && b - i <= 4){
					System.out.print("*");
				}
				else {
					System.out.print(" ");
				}
			}
		System.out.println();
		}
	}
}

**Comment by q123600** [comment]
###Part 4###
public class First {
	public static void main(String[] args) {
		
		for(int i = 0 ; i < 5 ; i += 1){
			for(int b = 0 ; b < 9 ; b += 1){
				if(b <= 4 && i >= b){
					System.out.print("*");
				}
				else if(b > 4 && b + i >= 8){
					System.out.print("*");
				}
				else {
					System.out.print(" ");
				}
			}
		System.out.println();
		}
	}
}

**Comment by PsMonkey** [comment]
請修改你的 markdown 語法，使其能在 github 上頭正常的顯示。

github 都有提供 preview 功能了，都不先看一下就 submit 出去嗎？ ＝＝"

**Comment by PsMonkey** [comment]
* 請修改你的 markdown 語法（每個 comment 都是可以修改的），使其能在 github 上頭正常的顯示。
    github 都有提供 preview 功能了，都不先看一下就 submit 出去嗎？ ＝＝"
* 一開始的 spec 有說了，節錄最直白的部份

    > 重點是「5」這個 magic number 除了在一開始宣告之外，後續程式碼不能出現。

    也就是說，你交上來的作業沒有一個符合 spec→通通 0 分的概念 :skull: 
* 想一下你在學 Python 的時候，老師 / 教科書上頭要求你的事情（想不出來的話，晚上會公佈謎底）。
    反過來說，如果你的學校老師 / 教科書都沒有要求那些事情，
    趕快換一間學校 / 換一本教科書...... :scream: 

請直接修改你的 comment 以 submit 新版本，全部修改完之後請再補一個 comment（這樣系統才會通知我）

**Comment by q123600** [comment]
應該是改完了（不確定有沒有漏）

**Comment by PsMonkey** [comment]
＝＝"... 需求！需求！需求！

> 當使用者輸入一個數字 n，要印出對應的圖形。

當 n = 6 或是其他值的時候，你的程式還會正常嗎？

**Comment by q123600** [comment]
我實在想不出你所說的更簡潔跟更直覺的方法..
